In [51]:
import torch
import torch.nn as nn

In [52]:
input_dim = 4
hidden_dim = 6
batch_size = 3
seq_len = 5

In [53]:
inp = torch.rand(size = (batch_size, seq_len, input_dim), dtype=torch.float)
inp.shape

torch.Size([3, 5, 4])

In [54]:
# hidden_state (= short-term memory)
hidden_state = torch.zeros(1,batch_size, hidden_dim, dtype=torch.float)

# cell_state (= long-term memory)
cell_state = torch.zeros(1, batch_size, hidden_dim, dtype=torch.float)

# hidden
hidden = (hidden_state, cell_state)

# LSTM 모델을 생성
lstm_layer = nn.LSTM(input_dim, hidden_dim, batch_first=True)

In [55]:
hidden_state

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [ ]:
out, hidden = lstm_layer(inp, hidden)
hidden[0]

tensor([[[ 0.0627,  0.0160, -0.0658, -0.1894, -0.2211,  0.1848],
         [ 0.0576, -0.1202, -0.0782, -0.2707, -0.2610,  0.1924],
         [ 0.0512, -0.0537, -0.0660, -0.2006, -0.2274,  0.2137]]],
       grad_fn=<StackBackward0>)

In [59]:
out[:,-1,:]

tensor([[ 0.0627,  0.0160, -0.0658, -0.1894, -0.2211,  0.1848],
        [ 0.0576, -0.1202, -0.0782, -0.2707, -0.2610,  0.1924],
        [ 0.0512, -0.0537, -0.0660, -0.2006, -0.2274,  0.2137]],
       grad_fn=<SliceBackward0>)